version: "3"
   
services:
  db:
    image: wnameless/oracle-xe-11g-r2
    ports:
      - 1521:1521
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db