version: "3"
   
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 1521:1521
  web:
    build: .
    command: python manage.py jenkins --enable-coverage
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db